name       : splix
version    : 2.0.0
release    : 1
source     :
    - https://pilotfiber.dl.sourceforge.net/project/splix/splix/2.0.0/splix-2.0.0.tar.bz2 : 97f703fc73a2940e63da43130615f3ef2a06d4d1f85fe6edfed0c0cd79de912f
license    : GPL-2.0
component  : desktop.core
summary    : This driver is usable by all printer devices which understand the QPDL (Quick Page Description Language) language
description: |
    This driver is usable by all printer devices which understand the QPDL (Quick Page Description Language) language
builddeps  :
    - cups-devel
rundeps    :
    - ghostscript
setup      : |
    %patch -p1 -l < $pkgfiles/libs.patch
    %patch -p1 -l < $pkgfiles/gcc45.patch
build      : |
    export CFLAGS="$CFLAGS -fno-strict-aliasing"
    export CXXFLAGS="$CXXFLAGS -fno-strict-aliasing -std=c++0x"
    %make DISABLE_JBIG=1
install    : |
    %make_install DISABLE_JBIG=1
